"""Render a whole *suite* of verdicts as one self-contained, browsable HTML page.

``atf eval --cases FILE`` runs many cases through the tribunal; this turns the resulting
``(name, verdict)`` list into a single page with a summary header, a one-row-per-case table
of anchor links, and a per-case section below carrying that case's rationale, cited findings,
and full evidence ledger (advisory findings split into their own muted block, exactly as the
single-verdict report does). The finding/severity styling and the HTML-escaping discipline
are shared with :mod:`agentic_testing_framework.reporting.html` — every dynamic value is
passed through :func:`html.escape`, so a finding whose message contains markup is shown as
text, never interpreted.

Standard library only: :class:`string.Template` for the document shell, :func:`html.escape`
for every dynamic value. No templating engine, no external assets — the output is one file.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from html import escape
from string import Template
from typing import TYPE_CHECKING

from .html import _STYLE, _render_finding

if TYPE_CHECKING:
    from ..core.finding import Finding
    from ..core.types import Verdict

# A small amount of suite-only styling layered on top of the shared single-report style: the
# summary counters, the case index table, and the per-case section dividers.
_SUITE_STYLE = """
  .summary { display: flex; flex-wrap: wrap; gap: 0.6rem; margin: 0.75rem 0 0; }
  .stat { display: inline-flex; flex-direction: column; align-items: center; min-width: 5rem;
          padding: 0.5rem 0.9rem; border: 1px solid #e2e2e2; border-radius: 0.5rem;
          background: #fff; }
  .stat-n { font-size: 1.4rem; font-weight: 700; line-height: 1; }
  .stat-label { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em;
                color: #777; margin-top: 0.2rem; }
  .stat-pass .stat-n { color: #186a3b; }
  .stat-fail .stat-n { color: #a01a0e; }
  .stat-inconclusive .stat-n { color: #8a5300; }
  table.cases td.name a { text-decoration: none; color: #224; font-weight: 600; }
  table.cases td.name a:hover { text-decoration: underline; }
  .badge { display: inline-block; padding: 0.1rem 0.55rem; border-radius: 0.35rem;
           font-size: 0.72rem; font-weight: 700; text-transform: uppercase;
           letter-spacing: 0.03em; }
  .badge-pass { background: #e7f6ec; color: #186a3b; }
  .badge-fail { background: #fdecea; color: #a01a0e; }
  .badge-inconclusive { background: #fff4e5; color: #8a5300; }
  .case-block { border-top: 1px solid #ddd; margin-top: 1.5rem; padding-top: 0.5rem; }
  .case-block h2 { border-bottom: none; }
  .backlink { font-size: 0.8rem; }
  .backlink a { color: #888; text-decoration: none; }
  .backlink a:hover { text-decoration: underline; }
"""

_DOCUMENT = Template(
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<style>$style$suite_style</style>
</head>
<body>
<main>
<header id="top">
<h1>$title</h1>
<p class="meta">$total case(s) judged through the tribunal.</p>
<div class="summary">$summary</div>
</header>
<h2>Cases</h2>
$table
$sections
<footer>Generated by the Agentic Testing Framework tribunal.</footer>
</main>
</body>
</html>
"""
)


def render_suite_html(
    results: Sequence[tuple[str, Verdict]],
    *,
    title: str = "Agentic Testing Framework — Suite",
) -> str:
    """Render a suite of ``(name, verdict)`` results as one self-contained HTML document.

    Args:
        results: the per-case ``(name, verdict)`` pairs, in run order.
        title: the document title and page header.

    Returns:
        A complete HTML document as a string. Every dynamic value is HTML-escaped, and each
        table row anchor-links to that case's section further down the page.
    """

    n_pass = sum(1 for _, v in results if v.outcome.value == "pass")
    n_fail = sum(1 for _, v in results if v.outcome.value == "fail")
    n_inconclusive = sum(1 for _, v in results if v.outcome.value == "inconclusive")
    summary = "".join(
        _stat(n, label, css)
        for n, label, css in (
            (len(results), "total", "total"),
            (n_pass, "pass", "pass"),
            (n_fail, "fail", "fail"),
            (n_inconclusive, "inconclusive", "inconclusive"),
        )
    )
    # One stable anchor per case, deduped so two cases sharing a name still link distinctly.
    anchors = _anchors(name for name, _ in results)
    return _DOCUMENT.substitute(
        title=escape(title),
        style=_STYLE,
        suite_style=_SUITE_STYLE,
        total=len(results),
        summary=summary,
        table=_render_table(results, anchors),
        sections=_render_sections(results, anchors),
    )


def _stat(n: int, label: str, css: str) -> str:
    return (
        f"<div class='stat stat-{escape(css)}'>"
        f"<span class='stat-n'>{n}</span>"
        f"<span class='stat-label'>{escape(label)}</span></div>"
    )


def _anchors(names: Iterable[str]) -> list[str]:
    """Map each case name to a unique, URL-safe anchor id, preserving order.

    A name may repeat across a suite, so a numeric suffix disambiguates collisions and keeps
    every table link pointing at exactly one section.
    """

    anchors: list[str] = []
    seen: dict[str, int] = {}
    for i, name in enumerate(names):
        slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(name)).strip("-").lower() or "case"
        slug = f"case-{slug}"
        count = seen.get(slug, 0)
        seen[slug] = count + 1
        anchors.append(f"{slug}-{i}" if count else slug)
    return anchors


def _render_table(results: Sequence[tuple[str, Verdict]], anchors: Sequence[str]) -> str:
    if not results:
        return "<p class='meta'>No cases were run.</p>"
    rows = []
    for (name, verdict), anchor in zip(results, anchors, strict=False):
        outcome = verdict.outcome.value
        n_advisory = sum(1 for f in verdict.findings if f.advisory)
        n_findings = len(verdict.findings) - n_advisory
        rows.append(
            "<tr>"
            f"<td class='name'><a href='#{escape(anchor)}'>{escape(name)}</a></td>"
            f"<td><span class='badge badge-{escape(outcome)}'>{escape(outcome)}</span></td>"
            f"<td>{n_findings}</td>"
            f"<td>{n_advisory}</td>"
            "</tr>"
        )
    body = "\n".join(rows)
    return (
        "<table class='cases'>\n"
        "<tr><th>Case</th><th>Outcome</th><th>Findings</th><th>Advisory</th></tr>\n"
        f"{body}\n</table>"
    )


def _render_sections(results: Sequence[tuple[str, Verdict]], anchors: Sequence[str]) -> str:
    sections = []
    for (name, verdict), anchor in zip(results, anchors, strict=False):
        sections.append(_render_section(name, verdict, anchor))
    return "\n".join(sections)


def _render_section(name: str, verdict: Verdict, anchor: str) -> str:
    outcome = verdict.outcome.value
    ledger_findings = tuple(f for f in verdict.findings if not f.advisory)
    advisory_findings = tuple(f for f in verdict.findings if f.advisory)
    rationale = escape(verdict.rationale) or "<em>(no rationale)</em>"
    return (
        f"<section class='case-block' id='{escape(anchor)}'>\n"
        f"<h2>{escape(name)} "
        f"<span class='badge badge-{escape(outcome)}'>{escape(outcome)}</span></h2>\n"
        "<p class='backlink'><a href='#top'>&uarr; back to top</a></p>\n"
        f"<div class='rationale'>{rationale}</div>\n"
        "<h3>Cited findings</h3>\n"
        f"{_render_cited(verdict)}\n"
        "<h3>Evidence ledger</h3>\n"
        f"{_render_ledger(ledger_findings)}\n"
        f"{_render_advisory(advisory_findings)}\n"
        "</section>"
    )


def _render_cited(verdict: Verdict) -> str:
    if not verdict.cited_findings:
        return "<p class='meta'>No findings were cited.</p>"
    items = "\n".join(f"<li>{escape(str(fid))}</li>" for fid in verdict.cited_findings)
    return f"<ul class='cited'>\n{items}\n</ul>"


def _render_ledger(findings: tuple[Finding, ...]) -> str:
    if not findings:
        return "<p class='meta'>The ledger is empty.</p>"
    grouped: dict[str, list[Finding]] = {}
    for finding in findings:
        grouped.setdefault(finding.source, []).append(finding)
    sections = []
    for source, group in grouped.items():
        ordered = sorted(group, key=lambda f: f.severity.rank, reverse=True)
        cards = "\n".join(_render_finding(f) for f in ordered)
        sections.append(f"<h4>{escape(source)}</h4>\n{cards}")
    return "\n".join(sections)


def _render_advisory(findings: tuple[Finding, ...]) -> str:
    """Render advisory (beyond-spec) findings in their own muted block, or nothing.

    Mirrors the single-verdict report: these are true observations the stated
    expectation/criteria did not require, surfaced for the reader but kept SEPARATE from the
    verdict-driving ledger. When there are none, emit nothing so a clean case stays clean.
    """

    if not findings:
        return ""
    grouped: dict[str, list[Finding]] = {}
    for finding in findings:
        grouped.setdefault(finding.source, []).append(finding)
    sections = []
    for source, group in grouped.items():
        ordered = sorted(group, key=lambda f: f.severity.rank, reverse=True)
        cards = "\n".join(_render_finding(f) for f in ordered)
        sections.append(f"<h4>{escape(source)}</h4>\n{cards}")
    body = "\n".join(sections)
    return (
        "<h3>Also noted — advisory (beyond the stated spec)</h3>\n"
        "<p class='advisory-note'>True observations the stated expectation/criteria did not "
        "require. Recorded for context; they did not affect the verdict.</p>\n"
        f"<div class='advisory'>\n{body}\n</div>"
    )
